version: "3.9"

services:
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
      - SYSTEM_ENV=PRODUCTION
      - SECRET_KEY=SECRET_KEY
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASSWORD=secret
      - ADMIN=admin
      - DEBUG=1
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python import_csv.py &&
             python manage.py runserver 0.0.0.0:8000"
volumes:
  postgres_data:
    driver: local
