name: Terraform destroy


on:
  workflow_dispatch:
jobs:

  destroy:
    name: 'Terraform destroy'
    runs-on: ubuntu-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./deploy/terraform/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.0.5

      - name: Terraform destroy staging
        id: destroy-staging
        if: ${{ github.ref != 'refs/heads/staging' }}
        run: |
          terraform init
          terraform workspace select staging
          terraform destroy -auto-approve
      - name: Terraform destroy production
        id: destroy-production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: |
          terraform init
          terraform workspace select production
          terraform destroy -auto-approve
